<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>CleanDDDArchitecture.Domains.Weather.Tests.Behaviour</RootNamespace>
        <AssemblyName>CleanDDDArchitecture.Domains.Weather.Tests.Behaviour</AssemblyName>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="coverlet.collector">
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="FluentAssertions" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" />
      <PackageReference Include="xunit.v3" />
      <PackageReference Include="xunit.runner.visualstudio">
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Application\Application.csproj" />
    </ItemGroup>

</Project>
