---
UseInMemoryDatabase: false
ConnectionStrings:
  DefaultWriteConnection: User ID =panosru;Password=123123;Server=localhost;Port=5432;Database=CleanDDDArchitecture;Integrated Security=true;Pooling=true;
  DefaultReadConnection: User ID =panosru;Password=123123;Server=localhost;Port=5432;Database=CleanDDDArchitecture;Integrated Security=true;Pooling=true;
  mongo: mongodb://127.0.0.1:27017
Logging:
  LogLevel:
    Default: Debug
    System: Information
    Microsoft: Information
SwaggerSettings:
  RoutePrefix: ''
FeatureManagement:
  Metal: true