---
AllowedHosts: "*"
UseInMemoryDatabase: false

SwaggerSettings:
  Name: CleanDDD API
  RoutePrefix: docs
  DefaultApiVersion:
    Major: 1
    Minor: 0
  Info:
    Title: Rest API
    Description: Swagger with API version, <a href='/swagger.yaml'>download swagger.yaml</a>
    TermsOfService: https://company.com/termsofservice
    Contact:
      Name: John Doe
      Email: j.doe@email.com
      Url: https://support.company.com/helpdesk
    License:
      Name: MIT
      Url: https://opensource.org/licenses/MIT

Logging:
  LogLevel:
  Default: Warning

Serilog:
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft: Warning
      System: Warning
  WriteTo:
    - Name: RollingFile
      Args:
        pathFormat: logs\log-{Date}.txt
        outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] [{SourceContext}] {Message}{NewLine}{Exception}"
        rollingInterval: Day
        rollOnFileSizeLimit: true
        fileSizeLimitBytes: '10485760'
  Enrich:
    - FromLogContext
    - WithMachineName
    - WithThreadId

FeatureManagement:
  Metal: true