---
IdentityServer:
  Key:
    Type: Store
    StoreName: My
    StoreLocation: CurrentUser
    Name: CN=MyApplication

Logging:
  LogLevel:
    Default: Debug
    System: Information
    Microsoft: Information