<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>CleanDDDArchitecture.Hosts.Services.TodoService.Presentation</RootNamespace>
    <AssemblyName>CleanDDDArchitecture.Hosts.Services.TodoService.Presentation</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Domains\Todo\Hosts\RestApi\Presentation\Presentation.csproj" />
    <ProjectReference Include="..\..\..\ServiceDefaults\Core\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="appsettings.Development.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <DependentUpon>appsettings.yaml</DependentUpon>
    </Content>
  </ItemGroup>
</Project>
