<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>CleanDDDArchitecture.Hosts.Gateway.Presentation</RootNamespace>
    <AssemblyName>CleanDDDArchitecture.Hosts.Gateway.Presentation</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetEscapades.Configuration.Yaml" />
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="appsettings.Development.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <DependentUpon>appsettings.yaml</DependentUpon>
    </Content>
  </ItemGroup>
</Project>
