version: '3.9'

services:
  
  mssqladmin:
    extends:
      file:    ./services/mssql.yaml
      service: mssqladmin
    ports:
      - ${MSSQLADMIN_PUBLIC_PORT}:${MSSQLADMIN_PORT}
    networks:
      - cleandddarchitecture_mssql_net
    volumes:
      - dbeaver_data:/opt/cloudbeaver/workspace
      - ./services/cloudbeaver.json:/opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
    environment:
      CB_SERVER_URL: http://localhost:${MSSQLADMIN_PUBLIC_PORT}
  
  pgadmin:
    extends:
      file:    ./services/postgres.yaml
      service: pgadmin
    ports:
      - "${PGADMIN_PUBLIC_PORT}:80"
    networks:
      - cleandddarchitecture_postgres_net
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./services/pgadmin_servers.json:/pgadmin4/servers.json
  
  redis-commander:
    extends:
      file:    ./services/redis.yaml
      service: redis-commander
    ports:
      - ${REDIS_COMMANDER_PUBLIC_PORT}:${REDIS_COMMANDER_PORT}
    networks:
      - cleandddarchitecture_redis_net
  
  grafana:
    extends:
      file:    ./services/monitor.yaml
      service: grafana
    ports:
      - ${GRAFANA_PUBLIC_PORT}:${GRAFANA_PORT}
    networks:
      - cleandddarchitecture_monitor_net
    volumes:
      - grafana_data:/var/lib/grafana
      - ./services/grafana/provisioning/:/etc/grafana/provisioning/
  
#  kafka-ui:
#    extends:
#      file:    ./services/kafka.yaml
#      service: kafka-ui
#    ports:
#      - "${KAFKA_UI_PUBLIC_PORT}:8080"
#    networks:
#      - cleandddarchitecture_kafka_net
  
  kowl:
    extends:
      file:    ./services/kafka.yaml
      service: kowl
    ports:
      - "${KOWL_PUBLIC_PORT}:8080"
    networks:
      - cleandddarchitecture_kafka_net
  
# Volumes
volumes:
  dbeaver_data:
    name: ${MSSQLADMIN_HOST}-data
  grafana_data:
    name: ${GRAFANA_HOST}-data
  pgadmin_data:
    name: ${PGADMIN_HOST}-data

# Networks
networks:
  cleandddarchitecture_mssql_net:
    external: true
  cleandddarchitecture_postgres_net:
    external: true
  cleandddarchitecture_redis_net:
    external: true
  cleandddarchitecture_monitor_net:
    external: true
  cleandddarchitecture_kafka_net:
    external: true
