ConnectionStrings:
  Hangfire: "User ID=panosru;Password=rX3t9bvDT2ftH2;Server=localhost;Port=15432;Database=Hangfire;Integrated Security=true;Pooling=false;Maximum Pool Size=500;ConnectionIdleLifetime=5;ConnectionPruningInterval=2"
Logging:
  LogLevel:
    Default: "Information"
    Microsoft: "Warning"
    Microsoft.Hosting.Lifetime: "Information"
AllowedHosts: "*"
