---
eventsTopicName: "CleanDDDArchitectureEvents"
eventsTopicGroupName: "cleandddarchitecture-api-events-consumer"

FeatureManagement:
  AccountCreate: true
  AccountAuthentication: true
  AccountConfirmEmail: true
  AccountGetBy: true
  AccountProfile: true
  AccountUpdateDetails: true