---
eventsTopicName: "CleanDDDArchitectureEvents"
eventsTopicGroupName: "cleandddarchitecture-api-events-consumer"

Jwt:
  ExpirationDurationInMunuts: 30
  ClockSkewInMinutes: 5

FeatureManagement:
  AccountCreate: true
  AccountAuthentication: true
  AccountConfirmEmail: true
  AccountGetBy: true
  AccountProfile: true
  AccountUpdateDetails: true
