---
eventsTopicName: "CleanDDDArchitectureEvents"
eventsTopicGroupName: "cleandddarchitecture-api-events-consumer"

Auth:
  Cookie:
    Name: "CleanDDDArchitecture.Hosts.RestApi.PresentationAPI"
    ExpireTimeSpanInMinutes: 15
    LoginPath: "/api/identity/authenticate"
    LogoutPath: "/api/identity/logout"
    SlidingExpiration: true
  IdentityOptions:
    Password:
      RequireDigit: true
      RequiredLength: 5
      RequireLowercase: true
      RequireUppercase: true
      RequireNonAlphanumeric: true
    Lockout:
      DefaultLockoutTimeSpanInMinutes: 10
      MaxFailedAccessAttempts: 3
    User:
      RequireUniqueEmail: true
    SignIn:
      RequireConfirmedEmail: true
      RequireConfirmedPhoneNumber: false
      RequireConfirmedAccount: false

FeatureManagement:
  AccountCreate: true
  AccountAuthentication: true
  Account2fa: true
  AccountForgotPassword: true
  AccountResetPassword: true
  AccountRefreshToken: true
  AccountConfirmEmail: true
  AccountGetBy: true
  AccountProfile: true
  AccountUpdateDetails: true
