<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>CleanDDDArchitecture.Domains.Account.Infrastructure</RootNamespace>
        <AssemblyName>CleanDDDArchitecture.Domains.Account.Infrastructure</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
        <_Parameter1>CleanDDDArchitecture.Domains.Account.Tests.Unit</_Parameter1>
      </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Persistence\Migrations" />
    </ItemGroup>

    <ItemGroup>
        <None Remove=".gitignore" />
        <None Remove="Persistence\Migrations\.gitkeep" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Library\Aviant\src\Identity\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\..\..\Library\Aviant\src\EventSourcing\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\..\..\Library\Aviant\src\Persistence\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\..\Shared\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

</Project>
