version: '3.9'

services:
  loki:
    image: grafana/loki:main
    restart: 'no'
    container_name: ${LOKI_HOST}
    logging:
      driver: "json-file"
      options:
        max-size: 2m
        max-file: '3'
    expose:
      - ${LOKI_PORT}
    command: -config.file=/etc/loki/loki-config.yaml -config.expand-env=true -querier.max-query-lookback=0s

  grafana:
    image: grafana/grafana:latest
    restart: 'no'
    container_name: ${GRAFANA_HOST}
    logging:
      driver: "json-file"
      options:
        max-size: 2m
        max-file: '3'
    user: "0" # To allow Grafana to boot up
    expose:
      - ${GRAFANA_PORT}
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_SECURITY_ADMIN_PASSWORD}
