-- Database bootstrap is intentionally minimal.
-- The main application database is created by the postgres image via POSTGRES_DB,
-- and schema creation is handled by application migrations on startup.
