name: Clean DDD Architecture .NET Core Template

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.6.22352.1
    - name: Install dotnet ef
      run: dotnet tool install --global dotnet-ef --version 7.0.0-preview.6.22329.4
    - name: Build with dotnet
      run: dotnet build --configuration Release
